name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
        platform:
          - { target: nightly-x86_64-pc-windows-msvc, os: windows-latest, ext: ".exe" }
          - { target: nightly-x86_64-unknown-linux-gnu, os: ubuntu-latest, ext: "" }
          - { target: nightly-x86_64-apple-darwin, os: macos-latest, ext: "" }
          - { target: nightly-aarch64-apple-ios, os: macos-latest, ext: "" }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v2
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-01-16
          target: ${{ matrix.platform.target }}

      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libgtksourceview-3.0-dev libappindicator3-dev
      - name: install webview2 (windows only)
        if: matrix.platform.os == 'windows-latest'
        shell: pwsh
        run: |
          Invoke-WebRequest https://go.microsoft.com/fwlink/p/?LinkId=2124703 -OutFile installwebview.exe -UseBasicParsing
          cmd /C start /wait installwebview.exe /silent /install
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Cache cargo registry
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cargo/registry
          # Add date to the cache to keep it up to date
          key: ${{ matrix.platform }}-stable-cargo-registry-${{ hashFiles('Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.platform }}-stable-cargo-registry-${{ hashFiles('Cargo.toml') }}
            ${{ matrix.platform }}-stable-cargo-registry-
      - name: Cache cargo index
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cargo/git
          # Add date to the cache to keep it up to date
          key: ${{ matrix.platform }}-stable-cargo-index-${{ hashFiles('Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.platform }}-stable-cargo-index-${{ hashFiles('Cargo.toml') }}
            ${{ matrix.platform }}-stable-cargo-index-
      - name: Cache cargo target
        uses: actions/cache@v2
        with:
          path: target
          # Add date to the cache to keep it up to date
          key: ${{ matrix.platform }}-stable-cargo-core-${{ hashFiles('Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.platform }}-stable-cargo-core-${{ hashFiles('Cargo.toml') }}
            ${{ matrix.platform }}-stable-cargo-core-
      - name: build release
        run: cargo build --release --workspace --target ${{ matrix.platform.target }}
      - name: List target folder
        run: ls . && ls ./target && ls ./target/${{ matrix.platform.target }}/release
      - name: Make Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref }}_${{ matrix.platform_target }}
          files: |
            ./target/${{ matrix.platform.target }}/release/sbbw${{ matrix.platform.ext }}
            ./target/${{ matrix.platform.target }}/release/sbbw-widget${{ matrix.platform.ext }}
